 # The try block lets you test a block of code for errors.

# The except block lets you handle the error.

# The finally block lets you execute code, 
# regardless of the result of the try- and except blocks.

# x='haii'
# print(x)

# try:
# #   x=9
#   print(x)
# except:
#   print("error occurred")



try:
    # v=5
    print(v)
except:
  print("Something went wrong")
else:
  print("Nothing went wrong")
finally:
    print('cmplt')



# try:
#     # y="hiii"
#     a=[3,65,4,2]
#     print(a[1])
#     print(y)
# except NameError:
#   print("name error went wrong")
# except IndexError:
#     print('indendation')  
# finally:
#   print("The 'try except' is finished")


# x = -21

# if x < 0:
#     raise Exception("Sorry, no numbers below zero")


# x = '6'

# if not type(x) is int:
  
#   raise IndexError("Only integers are dfsdfsdfsdfdsf")   


# a=4/0
# print(a)

